# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dingfeiPG <- function(X, lambda, Omega, index, maxinteration) {
    .Call('_dingfeiPG_dingfeiPG', PACKAGE = 'dingfeiPG', X, lambda, Omega, index, maxinteration)
}

